// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Challenge struct {
	ID       int32  `json:"id"`
	Title    string `json:"title"`
	Category string `json:"category"`
	Author   string `json:"author"`
	Text     string `json:"text"`
	TextHash string `json:"text_hash"`
}

type MultiChallengeStat struct {
	SessionID   string           `json:"session_id"`
	UserID      int32            `json:"user_id"`
	ChallengeID int32            `json:"challenge_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	TimeTaken   int32            `json:"time_taken"`
	Wpm         int32            `json:"wpm"`
	Accuracy    pgtype.Numeric   `json:"accuracy"`
	NumPlayers  int32            `json:"num_players"`
	Position    int32            `json:"position"`
}

type SingleChallengeStat struct {
	UserID      int32            `json:"user_id"`
	ChallengeID int32            `json:"challenge_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	TimeTaken   int32            `json:"time_taken"`
	Wpm         int32            `json:"wpm"`
	Accuracy    pgtype.Numeric   `json:"accuracy"`
}

type User struct {
	ID           int32            `json:"id"`
	Username     string           `json:"username"`
	PasswordHash string           `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type UserOverviewStat struct {
	UserID           int32 `json:"user_id"`
	SingleTotalRaces int32 `json:"single_total_races"`
	SingleTotalTime  int32 `json:"single_total_time"`
	SingleAvgWpm     int32 `json:"single_avg_wpm"`
	MultiTotalRaces  int32 `json:"multi_total_races"`
	MultiTotalTime   int32 `json:"multi_total_time"`
	MultiAvgWpm      int32 `json:"multi_avg_wpm"`
}
