// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: challenges.sql

package db

import (
	"context"
)

const getChallengeByID = `-- name: GetChallengeByID :one
SELECT id, title, author, text, category_id
FROM challenges
WHERE id = $1
`

func (q *Queries) GetChallengeByID(ctx context.Context, id int32) (Challenge, error) {
	row := q.db.QueryRow(ctx, getChallengeByID, id)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Text,
		&i.CategoryID,
	)
	return i, err
}

const getChallengesByCategory = `-- name: GetChallengesByCategory :many
SELECT challenges.id, title, author, text, category_id, categories.id, name
FROM challenges
JOIN categories ON challenges.category_id = categories.id
WHERE categories.id = $1
`

type GetChallengesByCategoryRow struct {
	ID         int32  `json:"id"`
	Title      string `json:"title"`
	Author     string `json:"author"`
	Text       string `json:"text"`
	CategoryID int32  `json:"category_id"`
	ID_2       int32  `json:"id_2"`
	Name       string `json:"name"`
}

func (q *Queries) GetChallengesByCategory(ctx context.Context, id int32) ([]GetChallengesByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getChallengesByCategory, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChallengesByCategoryRow
	for rows.Next() {
		var i GetChallengesByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Text,
			&i.CategoryID,
			&i.ID_2,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
