// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: multi_challenge_stats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMultiChallengeStats = `-- name: CreateMultiChallengeStats :one
INSERT INTO multi_challenge_stats (session_id, user_id, challenge_id, created_at, time_taken, wpm, accuracy, num_players, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING session_id, user_id, challenge_id, created_at, time_taken, wpm, accuracy, num_players, position
`

type CreateMultiChallengeStatsParams struct {
	SessionID   string           `json:"session_id"`
	UserID      int32            `json:"user_id"`
	ChallengeID int32            `json:"challenge_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	TimeTaken   int32            `json:"time_taken"`
	Wpm         int32            `json:"wpm"`
	Accuracy    pgtype.Numeric   `json:"accuracy"`
	NumPlayers  int32            `json:"num_players"`
	Position    int32            `json:"position"`
}

func (q *Queries) CreateMultiChallengeStats(ctx context.Context, arg CreateMultiChallengeStatsParams) (MultiChallengeStat, error) {
	row := q.db.QueryRow(ctx, createMultiChallengeStats,
		arg.SessionID,
		arg.UserID,
		arg.ChallengeID,
		arg.CreatedAt,
		arg.TimeTaken,
		arg.Wpm,
		arg.Accuracy,
		arg.NumPlayers,
		arg.Position,
	)
	var i MultiChallengeStat
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.ChallengeID,
		&i.CreatedAt,
		&i.TimeTaken,
		&i.Wpm,
		&i.Accuracy,
		&i.NumPlayers,
		&i.Position,
	)
	return i, err
}

const getMultiStatsByChallengeID = `-- name: GetMultiStatsByChallengeID :many
SELECT session_id, user_id, challenge_id, created_at, time_taken, wpm, accuracy, num_players, position
FROM multi_challenge_stats
WHERE challenge_id = $1
`

func (q *Queries) GetMultiStatsByChallengeID(ctx context.Context, challengeID int32) ([]MultiChallengeStat, error) {
	rows, err := q.db.Query(ctx, getMultiStatsByChallengeID, challengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MultiChallengeStat
	for rows.Next() {
		var i MultiChallengeStat
		if err := rows.Scan(
			&i.SessionID,
			&i.UserID,
			&i.ChallengeID,
			&i.CreatedAt,
			&i.TimeTaken,
			&i.Wpm,
			&i.Accuracy,
			&i.NumPlayers,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMultiStatsByUserID = `-- name: GetMultiStatsByUserID :many
SELECT session_id, user_id, challenge_id, created_at, time_taken, wpm, accuracy, num_players, position
FROM multi_challenge_stats
WHERE user_id = $1
`

func (q *Queries) GetMultiStatsByUserID(ctx context.Context, userID int32) ([]MultiChallengeStat, error) {
	rows, err := q.db.Query(ctx, getMultiStatsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MultiChallengeStat
	for rows.Next() {
		var i MultiChallengeStat
		if err := rows.Scan(
			&i.SessionID,
			&i.UserID,
			&i.ChallengeID,
			&i.CreatedAt,
			&i.TimeTaken,
			&i.Wpm,
			&i.Accuracy,
			&i.NumPlayers,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMultiStatsByUserIDAndChallengeID = `-- name: GetMultiStatsByUserIDAndChallengeID :one
SELECT session_id, user_id, challenge_id, created_at, time_taken, wpm, accuracy, num_players, position
FROM multi_challenge_stats
WHERE user_id = $1
  AND challenge_id = $2
`

type GetMultiStatsByUserIDAndChallengeIDParams struct {
	UserID      int32 `json:"user_id"`
	ChallengeID int32 `json:"challenge_id"`
}

func (q *Queries) GetMultiStatsByUserIDAndChallengeID(ctx context.Context, arg GetMultiStatsByUserIDAndChallengeIDParams) (MultiChallengeStat, error) {
	row := q.db.QueryRow(ctx, getMultiStatsByUserIDAndChallengeID, arg.UserID, arg.ChallengeID)
	var i MultiChallengeStat
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.ChallengeID,
		&i.CreatedAt,
		&i.TimeTaken,
		&i.Wpm,
		&i.Accuracy,
		&i.NumPlayers,
		&i.Position,
	)
	return i, err
}
