// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_overview_stats.sql

package db

import (
	"context"
)

const createUserOverviewStats = `-- name: CreateUserOverviewStats :one
INSERT INTO user_overview_stats (user_id, single_total_races, single_total_time, single_avg_wpm, multi_total_races,
                                 multi_total_time, multi_avg_wpm)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING user_id, single_total_races, single_total_time, single_avg_wpm, multi_total_races, multi_total_time, multi_avg_wpm
`

type CreateUserOverviewStatsParams struct {
	UserID           int32 `json:"user_id"`
	SingleTotalRaces int32 `json:"single_total_races"`
	SingleTotalTime  int32 `json:"single_total_time"`
	SingleAvgWpm     int32 `json:"single_avg_wpm"`
	MultiTotalRaces  int32 `json:"multi_total_races"`
	MultiTotalTime   int32 `json:"multi_total_time"`
	MultiAvgWpm      int32 `json:"multi_avg_wpm"`
}

func (q *Queries) CreateUserOverviewStats(ctx context.Context, arg CreateUserOverviewStatsParams) (UserOverviewStat, error) {
	row := q.db.QueryRow(ctx, createUserOverviewStats,
		arg.UserID,
		arg.SingleTotalRaces,
		arg.SingleTotalTime,
		arg.SingleAvgWpm,
		arg.MultiTotalRaces,
		arg.MultiTotalTime,
		arg.MultiAvgWpm,
	)
	var i UserOverviewStat
	err := row.Scan(
		&i.UserID,
		&i.SingleTotalRaces,
		&i.SingleTotalTime,
		&i.SingleAvgWpm,
		&i.MultiTotalRaces,
		&i.MultiTotalTime,
		&i.MultiAvgWpm,
	)
	return i, err
}

const getOverviewStatsByUserID = `-- name: GetOverviewStatsByUserID :one
SELECT user_id, single_total_races, single_total_time, single_avg_wpm, multi_total_races, multi_total_time, multi_avg_wpm
FROM user_overview_stats
WHERE user_id = $1
`

func (q *Queries) GetOverviewStatsByUserID(ctx context.Context, userID int32) (UserOverviewStat, error) {
	row := q.db.QueryRow(ctx, getOverviewStatsByUserID, userID)
	var i UserOverviewStat
	err := row.Scan(
		&i.UserID,
		&i.SingleTotalRaces,
		&i.SingleTotalTime,
		&i.SingleAvgWpm,
		&i.MultiTotalRaces,
		&i.MultiTotalTime,
		&i.MultiAvgWpm,
	)
	return i, err
}
