name: Update secrets

on:
  workflow_dispatch:

jobs:
  update-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Set secrets on OVH VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OVH_HOST }}
          username: ${{ secrets.OVH_USERNAME }}
          key: ${{ secrets.OVH_SSH_KEY }}
          script: |
            mkdir -p ~/typedash/secrets
            echo "${{ secrets.JWT_SECRET }}" > ~/typedash/secrets/jwt_secret
            echo "${{ secrets.POSTGRES_USER }}" > ~/typedash/secrets/postgres_user
            echo "${{ secrets.POSTGRES_PASSWORD }}" > ~/typedash/secrets/postgres_password
            echo "${{ secrets.POSTGRES_DB }}" > ~/typedash/secrets/postgres_db
            chmod 666 ~/typedash/secrets/*
